name: VKAFFApplicant
options:
  bundleIdPrefix: com.vkaff
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "2"
    INFOPLIST_KEY_UILaunchScreen_Generation: true
    INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
    GENERATE_INFOPLIST_FILE: true

targets:
  VKAFFApplicant:
    type: application
    platform: iOS
    sources:
      - path: VKAFFApplicant
        excludes:
          - Tests/**
          - Resources/service-account-key.json
    resources:
      - path: VKAFFApplicant/Resources/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.vkaff.applicant-kiosk
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_KEY_CFBundleDisplayName: "VKAFF Registration"
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.business"
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
    info:
      path: VKAFFApplicant/Info.plist
      properties:
        UILaunchScreen: {}

  VKAFFApplicantTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: VKAFFApplicant/Tests
    dependencies:
      - target: VKAFFApplicant
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.vkaff.applicant-kiosk.tests
